name: Continuous Integration

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        zig-version: ["0.14.0"]
        os: [macos-latest]
        include:
          - zig-version: "0.14.0"
            os: ubuntu-latest
            run: |
              sudo apt-get update
              sudo apt-get install -y build-essential lld llvm llvm-dev clang
          - zig-version: "0.14.0"
            os: macos-13 # Intel macOS

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}
          use-cache: false

      - name: Run `build`
        run: zig build --summary all
